version: '2'
services:
  web:
    image: gitea/gitea:1.13.1
    container_name: gitea
    volumes:
      - ./data:/data
    ports:
      - "8088:3000"
      - "2222:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    container_name: gitea_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Marx7476
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=Marx7476
    volumes:
      - ./db/:/var/lib/mysql
